# This is a basic workflow to help you get started with Actions

name: Linux CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Install Pip Packages
    - name: Build Solution
      run: "python -m pip install colorama pyinstaller requests"
    # Build
    - name: Package
      run:  pyinstaller -n CurseModpackDownloader --onefile --noupx "download.py"
    # chmod
    - name: chmod
      run: chmod +x "./dist/CurseModpackDownloader"
    # Upload Artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CurseModpackDownloader-dev
        path: /home/runner/work/curse-modpack-downloader/curse-modpack-downloader/dist/